### PR TITLE
Pattern property to use fast-glob

### PR DESCRIPTION
**Pull request by adessilly**
Pattern for fast-glob

### CODE REVIEW

**Comment by sibiraj-s** [comment]
I did the exact same thing I did previously. It was just being the master branch root cause for all the troubles 🤦

**Review by sibiraj-s — APPROVED** [review]

**Comment by sibiraj-s** [comment]
I will make some other changes in the repo. and publish this in v6 tomorrow

**Comment by sibiraj-s** [comment]
Published in v6.

**Comment by adessilly** [comment]
@sibiraj-s thx :-) !

**Pull request merged**
